/*
 * Created on 27 thg 10 2017 ( Time 09:54:52 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package org.ecomileage.bean.jpa;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonIgnore;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;


import javax.persistence.*;

/**
 * Persistent class for entity stored in table "campaign"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="campaign")
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="CampaignEntity.countAll", query="SELECT COUNT(x) FROM CampaignEntity x" )
} )
@DynamicInsert
@DynamicUpdate
public class CampaignEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer    id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="total_goal_CO2", nullable=false)
    private Float      totalGoalCo2 ;

    @Column(name="total_fact_CO2", nullable=false)
    private Float      totalFactCo2 ;

    @Column(name="total_goal_user", nullable=false)
    private Integer    totalGoalUser ;

    @Column(name="total_fact_user", nullable=false)
    private Integer    totalFactUser ;

    @Column(name="total_goal_tree", nullable=false)
    private Integer    totalGoalTree ;

    @Column(name="total_fact_tree", nullable=false)
    private Integer    totalFactTree ;

    @Column(name="year")
    private Integer    year         ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public CampaignEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id ) {
        this.id = id ;
    }
    public Integer getId() {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : total_goal_CO2 ( FLOAT ) 
    public void setTotalGoalCo2( Float totalGoalCo2 ) {
        this.totalGoalCo2 = totalGoalCo2;
    }
    public Float getTotalGoalCo2() {
        return this.totalGoalCo2;
    }

    //--- DATABASE MAPPING : total_fact_CO2 ( FLOAT ) 
    public void setTotalFactCo2( Float totalFactCo2 ) {
        this.totalFactCo2 = totalFactCo2;
    }
    public Float getTotalFactCo2() {
        return this.totalFactCo2;
    }

    //--- DATABASE MAPPING : total_goal_user ( INT ) 
    public void setTotalGoalUser( Integer totalGoalUser ) {
        this.totalGoalUser = totalGoalUser;
    }
    public Integer getTotalGoalUser() {
        return this.totalGoalUser;
    }

    //--- DATABASE MAPPING : total_fact_user ( INT ) 
    public void setTotalFactUser( Integer totalFactUser ) {
        this.totalFactUser = totalFactUser;
    }
    public Integer getTotalFactUser() {
        return this.totalFactUser;
    }

    //--- DATABASE MAPPING : total_goal_tree ( INT ) 
    public void setTotalGoalTree( Integer totalGoalTree ) {
        this.totalGoalTree = totalGoalTree;
    }
    public Integer getTotalGoalTree() {
        return this.totalGoalTree;
    }

    //--- DATABASE MAPPING : total_fact_tree ( INT ) 
    public void setTotalFactTree( Integer totalFactTree ) {
        this.totalFactTree = totalFactTree;
    }
    public Integer getTotalFactTree() {
        return this.totalFactTree;
    }

    //--- DATABASE MAPPING : year ( INT ) 
    public void setYear( Integer year ) {
        this.year = year;
    }
    public Integer getYear() {
        return this.year;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(id);
        sb.append("]:"); 
        sb.append(totalGoalCo2);
        sb.append("|");
        sb.append(totalFactCo2);
        sb.append("|");
        sb.append(totalGoalUser);
        sb.append("|");
        sb.append(totalFactUser);
        sb.append("|");
        sb.append(totalGoalTree);
        sb.append("|");
        sb.append(totalFactTree);
        sb.append("|");
        sb.append(year);
        return sb.toString(); 
    } 

}
