/*
 * Created on 27 thg 10 2017 ( Time 09:54:52 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.ecomileage.bean;

import java.io.Serializable;

import javax.validation.constraints.*;
import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;
@DynamicInsert
@DynamicUpdate
public class Campaign implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @NotNull
    private Integer id;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @NotNull
    private Float totalGoalCo2;

    @NotNull
    private Float totalFactCo2;

    @NotNull
    private Integer totalGoalUser;

    @NotNull
    private Integer totalFactUser;

    @NotNull
    private Integer totalGoalTree;

    @NotNull
    private Integer totalFactTree;


    private Integer year;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id ) {
        this.id = id ;
    }

    public Integer getId() {
        return this.id;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setTotalGoalCo2( Float totalGoalCo2 ) {
        this.totalGoalCo2 = totalGoalCo2;
    }
    public Float getTotalGoalCo2() {
        return this.totalGoalCo2;
    }

    public void setTotalFactCo2( Float totalFactCo2 ) {
        this.totalFactCo2 = totalFactCo2;
    }
    public Float getTotalFactCo2() {
        return this.totalFactCo2;
    }

    public void setTotalGoalUser( Integer totalGoalUser ) {
        this.totalGoalUser = totalGoalUser;
    }
    public Integer getTotalGoalUser() {
        return this.totalGoalUser;
    }

    public void setTotalFactUser( Integer totalFactUser ) {
        this.totalFactUser = totalFactUser;
    }
    public Integer getTotalFactUser() {
        return this.totalFactUser;
    }

    public void setTotalGoalTree( Integer totalGoalTree ) {
        this.totalGoalTree = totalGoalTree;
    }
    public Integer getTotalGoalTree() {
        return this.totalGoalTree;
    }

    public void setTotalFactTree( Integer totalFactTree ) {
        this.totalFactTree = totalFactTree;
    }
    public Integer getTotalFactTree() {
        return this.totalFactTree;
    }

    public void setYear( Integer year ) {
        this.year = year;
    }
    public Integer getYear() {
        return this.year;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
        public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(id);
        sb.append("|");
        sb.append(totalGoalCo2);
        sb.append("|");
        sb.append(totalFactCo2);
        sb.append("|");
        sb.append(totalGoalUser);
        sb.append("|");
        sb.append(totalFactUser);
        sb.append("|");
        sb.append(totalGoalTree);
        sb.append("|");
        sb.append(totalFactTree);
        sb.append("|");
        sb.append(year);
        return sb.toString(); 
    } 


}
