/*
 * Created on 30 thg 10 2017 ( Time 11:46:19 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.ecomileage.bean;

import java.io.Serializable;

import javax.validation.constraints.*;
import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;
import java.util.Date;
@DynamicInsert
@DynamicUpdate
public class MileageFavourite implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @NotNull
    private Integer id;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @NotNull
    private Integer userId;

    @NotNull
    private Double latStart;

    @NotNull
    private Double longStart;

    @NotNull
    private Double latEnd;

    @NotNull
    private Double longEnd;


    private Date createDate;


    private Date updateDate;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id ) {
        this.id = id ;
    }

    public Integer getId() {
        return this.id;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setUserId( Integer userId ) {
        this.userId = userId;
    }
    public Integer getUserId() {
        return this.userId;
    }

    public void setLatStart( Double latStart ) {
        this.latStart = latStart;
    }
    public Double getLatStart() {
        return this.latStart;
    }

    public void setLongStart( Double longStart ) {
        this.longStart = longStart;
    }
    public Double getLongStart() {
        return this.longStart;
    }

    public void setLatEnd( Double latEnd ) {
        this.latEnd = latEnd;
    }
    public Double getLatEnd() {
        return this.latEnd;
    }

    public void setLongEnd( Double longEnd ) {
        this.longEnd = longEnd;
    }
    public Double getLongEnd() {
        return this.longEnd;
    }

    public void setCreateDate( Date createDate ) {
        this.createDate = createDate;
    }
    public Date getCreateDate() {
        return this.createDate;
    }

    public void setUpdateDate( Date updateDate ) {
        this.updateDate = updateDate;
    }
    public Date getUpdateDate() {
        return this.updateDate;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
        public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(id);
        sb.append("|");
        sb.append(userId);
        sb.append("|");
        sb.append(latStart);
        sb.append("|");
        sb.append(longStart);
        sb.append("|");
        sb.append(latEnd);
        sb.append("|");
        sb.append(longEnd);
        sb.append("|");
        sb.append(createDate);
        sb.append("|");
        sb.append(updateDate);
        return sb.toString(); 
    } 


}
