/*
 * Created on 18 thg 12 2017 ( Time 11:22:32 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.ecomileage.bean;

import java.io.Serializable;

import javax.validation.constraints.*;
import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;
import java.util.Date;
@DynamicInsert
@DynamicUpdate
public class MileageApply implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @NotNull
    private Integer id;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    

    private Integer userId;


    private Integer giftId;


    private Integer pointUse;

    @Size( max = 300 )
    private String registerItem;

    @Size( max = 20 )
    private String postCode;

    @Size( max = 300 )
    private String address;

    @Size( max = 300 )
    private String addressDetail;


    private Boolean gender;

    @Size( max = 50 )
    private String age;

    @Size( max = 100 )
    private String job;

    @Size( max = 20 )
    private String phone;


    private Short type;

    @Size( max = 300 )
    private String memo;


    private Date updateDate;

    @NotNull
    private Short status;


    private Date createDate;


    private Short typeSend;

    @Size( max = 100 )
    private String couponNo;


    private Date expiredCouponTime;


    private Date sendCouponTime;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id ) {
        this.id = id ;
    }

    public Integer getId() {
        return this.id;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setUserId( Integer userId ) {
        this.userId = userId;
    }
    public Integer getUserId() {
        return this.userId;
    }

    public void setGiftId( Integer giftId ) {
        this.giftId = giftId;
    }
    public Integer getGiftId() {
        return this.giftId;
    }

    public void setPointUse( Integer pointUse ) {
        this.pointUse = pointUse;
    }
    public Integer getPointUse() {
        return this.pointUse;
    }

    public void setRegisterItem( String registerItem ) {
        this.registerItem = registerItem;
    }
    public String getRegisterItem() {
        return this.registerItem;
    }

    public void setPostCode( String postCode ) {
        this.postCode = postCode;
    }
    public String getPostCode() {
        return this.postCode;
    }

    public void setAddress( String address ) {
        this.address = address;
    }
    public String getAddress() {
        return this.address;
    }

    public void setAddressDetail( String addressDetail ) {
        this.addressDetail = addressDetail;
    }
    public String getAddressDetail() {
        return this.addressDetail;
    }

    public void setGender( Boolean gender ) {
        this.gender = gender;
    }
    public Boolean getGender() {
        return this.gender;
    }

    public void setAge( String age ) {
        this.age = age;
    }
    public String getAge() {
        return this.age;
    }

    public void setJob( String job ) {
        this.job = job;
    }
    public String getJob() {
        return this.job;
    }

    public void setPhone( String phone ) {
        this.phone = phone;
    }
    public String getPhone() {
        return this.phone;
    }

    public void setType( Short type ) {
        this.type = type;
    }
    public Short getType() {
        return this.type;
    }

    public void setMemo( String memo ) {
        this.memo = memo;
    }
    public String getMemo() {
        return this.memo;
    }

    public void setUpdateDate( Date updateDate ) {
        this.updateDate = updateDate;
    }
    public Date getUpdateDate() {
        return this.updateDate;
    }

    public void setStatus( Short status ) {
        this.status = status;
    }
    public Short getStatus() {
        return this.status;
    }

    public void setCreateDate( Date createDate ) {
        this.createDate = createDate;
    }
    public Date getCreateDate() {
        return this.createDate;
    }

    public void setTypeSend( Short typeSend ) {
        this.typeSend = typeSend;
    }
    public Short getTypeSend() {
        return this.typeSend;
    }

    public void setCouponNo( String couponNo ) {
        this.couponNo = couponNo;
    }
    public String getCouponNo() {
        return this.couponNo;
    }

    public void setExpiredCouponTime( Date expiredCouponTime ) {
        this.expiredCouponTime = expiredCouponTime;
    }
    public Date getExpiredCouponTime() {
        return this.expiredCouponTime;
    }

    public void setSendCouponTime( Date sendCouponTime ) {
        this.sendCouponTime = sendCouponTime;
    }
    public Date getSendCouponTime() {
        return this.sendCouponTime;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
        public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(id);
        sb.append("|");
        sb.append(userId);
        sb.append("|");
        sb.append(giftId);
        sb.append("|");
        sb.append(pointUse);
        sb.append("|");
        sb.append(registerItem);
        sb.append("|");
        sb.append(postCode);
        sb.append("|");
        sb.append(address);
        sb.append("|");
        sb.append(addressDetail);
        sb.append("|");
        sb.append(gender);
        sb.append("|");
        sb.append(age);
        sb.append("|");
        sb.append(job);
        sb.append("|");
        sb.append(phone);
        sb.append("|");
        sb.append(type);
        sb.append("|");
        sb.append(memo);
        sb.append("|");
        sb.append(updateDate);
        sb.append("|");
        sb.append(status);
        sb.append("|");
        sb.append(createDate);
        sb.append("|");
        sb.append(typeSend);
        sb.append("|");
        sb.append(couponNo);
        sb.append("|");
        sb.append(expiredCouponTime);
        sb.append("|");
        sb.append(sendCouponTime);
        return sb.toString(); 
    } 


}
