/*
 * Created on 8 thg 12 2017 ( Time 14:25:17 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.ecomileage.bean;

import java.io.Serializable;

import javax.validation.constraints.*;
import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;
import java.util.Date;
@DynamicInsert
@DynamicUpdate
public class Report implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @NotNull
    private Integer id;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @NotNull
    private Double latitude;

    @NotNull
    private Integer userId;

    @NotNull
    private Double longtitude;


    private Integer categoryId;

    @NotNull
    @Size( min = 1, max = 300 )
    private String title;

    @NotNull
    @Size( min = 1, max = 65535 )
    private String content;

    @NotNull
    @Size( min = 1, max = 500 )
    private String profileImage;

    @NotNull
    @Size( min = 1, max = 500 )
    private String profileUrl;


    private Date updateDate;


    private Date createDate;

    @NotNull
    private Short status;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id ) {
        this.id = id ;
    }

    public Integer getId() {
        return this.id;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setLatitude( Double latitude ) {
        this.latitude = latitude;
    }
    public Double getLatitude() {
        return this.latitude;
    }

    public void setUserId( Integer userId ) {
        this.userId = userId;
    }
    public Integer getUserId() {
        return this.userId;
    }

    public void setLongtitude( Double longtitude ) {
        this.longtitude = longtitude;
    }
    public Double getLongtitude() {
        return this.longtitude;
    }

    public void setCategoryId( Integer categoryId ) {
        this.categoryId = categoryId;
    }
    public Integer getCategoryId() {
        return this.categoryId;
    }

    public void setTitle( String title ) {
        this.title = title;
    }
    public String getTitle() {
        return this.title;
    }

    public void setContent( String content ) {
        this.content = content;
    }
    public String getContent() {
        return this.content;
    }

    public void setProfileImage( String profileImage ) {
        this.profileImage = profileImage;
    }
    public String getProfileImage() {
        return this.profileImage;
    }

    public void setProfileUrl( String profileUrl ) {
        this.profileUrl = profileUrl;
    }
    public String getProfileUrl() {
        return this.profileUrl;
    }

    public void setUpdateDate( Date updateDate ) {
        this.updateDate = updateDate;
    }
    public Date getUpdateDate() {
        return this.updateDate;
    }

    public void setCreateDate( Date createDate ) {
        this.createDate = createDate;
    }
    public Date getCreateDate() {
        return this.createDate;
    }

    public void setStatus( Short status ) {
        this.status = status;
    }
    public Short getStatus() {
        return this.status;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
        public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(id);
        sb.append("|");
        sb.append(latitude);
        sb.append("|");
        sb.append(userId);
        sb.append("|");
        sb.append(longtitude);
        sb.append("|");
        sb.append(categoryId);
        sb.append("|");
        sb.append(title);
        // attribute 'content' not usable (type = String Long Text)
        sb.append("|");
        sb.append(profileImage);
        sb.append("|");
        sb.append(profileUrl);
        sb.append("|");
        sb.append(updateDate);
        sb.append("|");
        sb.append(createDate);
        sb.append("|");
        sb.append(status);
        return sb.toString(); 
    } 


}
