/*
 * Created on 13 thg 12 2017 ( Time 17:11:43 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.ecomileage.bean;

import java.io.Serializable;

import javax.validation.constraints.*;
import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;
import java.util.Date;
@DynamicInsert
@DynamicUpdate
public class SupportBikeCenter implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @NotNull
    private Integer id;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    

    private Integer userId;


    private Double latitude;


    private Double longitude;


    private Double latCity;


    private Double longCity;


    private Double latDistrict;


    private Double longDistrict;

    @NotNull
    private Short type;

    @Size( max = 100 )
    private String city;

    @Size( max = 50 )
    private String postCode;

    @Size( max = 100 )
    private String district;

    @Size( max = 100 )
    private String name;

    @Size( max = 200 )
    private String trademark;

    @Size( max = 500 )
    private String homepage;

    @Size( max = 300 )
    private String address;

    @Size( max = 100 )
    private String phone;

    @Size( max = 100 )
    private String openTime;

    @NotNull
    private Integer totalBikeParking;

    @Size( max = 100 )
    private String closeTime;

    @NotNull
    private Integer totalBikeParkingFact;

    @Size( max = 200 )
    private String feeRental;

    @NotNull
    private Integer totalDoors;

    @Size( max = 100 )
    private String sourceInformation;

    @NotNull
    private Integer pumpBike;

    @Size( max = 300 )
    private String subname;


    private Date provideInformationDate;

    @Size( max = 50 )
    private String imageUrl;

    @Size( max = 50 )
    private String imageName;


    private Date createDate;


    private Date updateDate;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id ) {
        this.id = id ;
    }

    public Integer getId() {
        return this.id;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setUserId( Integer userId ) {
        this.userId = userId;
    }
    public Integer getUserId() {
        return this.userId;
    }

    public void setLatitude( Double latitude ) {
        this.latitude = latitude;
    }
    public Double getLatitude() {
        return this.latitude;
    }

    public void setLongitude( Double longitude ) {
        this.longitude = longitude;
    }
    public Double getLongitude() {
        return this.longitude;
    }

    public void setLatCity( Double latCity ) {
        this.latCity = latCity;
    }
    public Double getLatCity() {
        return this.latCity;
    }

    public void setLongCity( Double longCity ) {
        this.longCity = longCity;
    }
    public Double getLongCity() {
        return this.longCity;
    }

    public void setLatDistrict( Double latDistrict ) {
        this.latDistrict = latDistrict;
    }
    public Double getLatDistrict() {
        return this.latDistrict;
    }

    public void setLongDistrict( Double longDistrict ) {
        this.longDistrict = longDistrict;
    }
    public Double getLongDistrict() {
        return this.longDistrict;
    }

    public void setType( Short type ) {
        this.type = type;
    }
    public Short getType() {
        return this.type;
    }

    public void setCity( String city ) {
        this.city = city;
    }
    public String getCity() {
        return this.city;
    }

    public void setPostCode( String postCode ) {
        this.postCode = postCode;
    }
    public String getPostCode() {
        return this.postCode;
    }

    public void setDistrict( String district ) {
        this.district = district;
    }
    public String getDistrict() {
        return this.district;
    }

    public void setName( String name ) {
        this.name = name;
    }
    public String getName() {
        return this.name;
    }

    public void setTrademark( String trademark ) {
        this.trademark = trademark;
    }
    public String getTrademark() {
        return this.trademark;
    }

    public void setHomepage( String homepage ) {
        this.homepage = homepage;
    }
    public String getHomepage() {
        return this.homepage;
    }

    public void setAddress( String address ) {
        this.address = address;
    }
    public String getAddress() {
        return this.address;
    }

    public void setPhone( String phone ) {
        this.phone = phone;
    }
    public String getPhone() {
        return this.phone;
    }

    public void setOpenTime( String openTime ) {
        this.openTime = openTime;
    }
    public String getOpenTime() {
        return this.openTime;
    }

    public void setTotalBikeParking( Integer totalBikeParking ) {
        this.totalBikeParking = totalBikeParking;
    }
    public Integer getTotalBikeParking() {
        return this.totalBikeParking;
    }

    public void setCloseTime( String closeTime ) {
        this.closeTime = closeTime;
    }
    public String getCloseTime() {
        return this.closeTime;
    }

    public void setTotalBikeParkingFact( Integer totalBikeParkingFact ) {
        this.totalBikeParkingFact = totalBikeParkingFact;
    }
    public Integer getTotalBikeParkingFact() {
        return this.totalBikeParkingFact;
    }

    public void setFeeRental( String feeRental ) {
        this.feeRental = feeRental;
    }
    public String getFeeRental() {
        return this.feeRental;
    }

    public void setTotalDoors( Integer totalDoors ) {
        this.totalDoors = totalDoors;
    }
    public Integer getTotalDoors() {
        return this.totalDoors;
    }

    public void setSourceInformation( String sourceInformation ) {
        this.sourceInformation = sourceInformation;
    }
    public String getSourceInformation() {
        return this.sourceInformation;
    }

    public void setPumpBike( Integer pumpBike ) {
        this.pumpBike = pumpBike;
    }
    public Integer getPumpBike() {
        return this.pumpBike;
    }

    public void setSubname( String subname ) {
        this.subname = subname;
    }
    public String getSubname() {
        return this.subname;
    }

    public void setProvideInformationDate( Date provideInformationDate ) {
        this.provideInformationDate = provideInformationDate;
    }
    public Date getProvideInformationDate() {
        return this.provideInformationDate;
    }

    public void setImageUrl( String imageUrl ) {
        this.imageUrl = imageUrl;
    }
    public String getImageUrl() {
        return this.imageUrl;
    }

    public void setImageName( String imageName ) {
        this.imageName = imageName;
    }
    public String getImageName() {
        return this.imageName;
    }

    public void setCreateDate( Date createDate ) {
        this.createDate = createDate;
    }
    public Date getCreateDate() {
        return this.createDate;
    }

    public void setUpdateDate( Date updateDate ) {
        this.updateDate = updateDate;
    }
    public Date getUpdateDate() {
        return this.updateDate;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
        public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(id);
        sb.append("|");
        sb.append(userId);
        sb.append("|");
        sb.append(latitude);
        sb.append("|");
        sb.append(longitude);
        sb.append("|");
        sb.append(latCity);
        sb.append("|");
        sb.append(longCity);
        sb.append("|");
        sb.append(latDistrict);
        sb.append("|");
        sb.append(longDistrict);
        sb.append("|");
        sb.append(type);
        sb.append("|");
        sb.append(city);
        sb.append("|");
        sb.append(postCode);
        sb.append("|");
        sb.append(district);
        sb.append("|");
        sb.append(name);
        sb.append("|");
        sb.append(trademark);
        sb.append("|");
        sb.append(homepage);
        sb.append("|");
        sb.append(address);
        sb.append("|");
        sb.append(phone);
        sb.append("|");
        sb.append(openTime);
        sb.append("|");
        sb.append(totalBikeParking);
        sb.append("|");
        sb.append(closeTime);
        sb.append("|");
        sb.append(totalBikeParkingFact);
        sb.append("|");
        sb.append(feeRental);
        sb.append("|");
        sb.append(totalDoors);
        sb.append("|");
        sb.append(sourceInformation);
        sb.append("|");
        sb.append(pumpBike);
        sb.append("|");
        sb.append(subname);
        sb.append("|");
        sb.append(provideInformationDate);
        sb.append("|");
        sb.append(imageUrl);
        sb.append("|");
        sb.append(imageName);
        sb.append("|");
        sb.append(createDate);
        sb.append("|");
        sb.append(updateDate);
        return sb.toString(); 
    } 


}
