/*
 * Created on 6 thg 11 2017 ( Time 16:54:14 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.ecomileage.bean;

import java.io.Serializable;

import javax.validation.constraints.*;
import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;
import java.util.Date;
@DynamicInsert
@DynamicUpdate
public class TeamMember implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @NotNull
    private Integer id;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    

    private Integer groupId;


    private Integer memberId;

    @NotNull
    private Integer totalMileage;

    @NotNull
    private Integer totalReduceCo2;

    @NotNull
    private Integer totalTree;

    @NotNull
    private Boolean isManager;

    @NotNull
    private Short status;


    private Date createDate;

    @NotNull
    private Boolean isDelete;


    private Date updateDate;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id ) {
        this.id = id ;
    }

    public Integer getId() {
        return this.id;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setGroupId( Integer groupId ) {
        this.groupId = groupId;
    }
    public Integer getGroupId() {
        return this.groupId;
    }

    public void setMemberId( Integer memberId ) {
        this.memberId = memberId;
    }
    public Integer getMemberId() {
        return this.memberId;
    }

    public void setTotalMileage( Integer totalMileage ) {
        this.totalMileage = totalMileage;
    }
    public Integer getTotalMileage() {
        return this.totalMileage;
    }

    public void setTotalReduceCo2( Integer totalReduceCo2 ) {
        this.totalReduceCo2 = totalReduceCo2;
    }
    public Integer getTotalReduceCo2() {
        return this.totalReduceCo2;
    }

    public void setTotalTree( Integer totalTree ) {
        this.totalTree = totalTree;
    }
    public Integer getTotalTree() {
        return this.totalTree;
    }

    public void setIsManager( Boolean isManager ) {
        this.isManager = isManager;
    }
    public Boolean getIsManager() {
        return this.isManager;
    }

    public void setStatus( Short status ) {
        this.status = status;
    }
    public Short getStatus() {
        return this.status;
    }

    public void setCreateDate( Date createDate ) {
        this.createDate = createDate;
    }
    public Date getCreateDate() {
        return this.createDate;
    }

    public void setIsDelete( Boolean isDelete ) {
        this.isDelete = isDelete;
    }
    public Boolean getIsDelete() {
        return this.isDelete;
    }

    public void setUpdateDate( Date updateDate ) {
        this.updateDate = updateDate;
    }
    public Date getUpdateDate() {
        return this.updateDate;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
        public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(id);
        sb.append("|");
        sb.append(groupId);
        sb.append("|");
        sb.append(memberId);
        sb.append("|");
        sb.append(totalMileage);
        sb.append("|");
        sb.append(totalReduceCo2);
        sb.append("|");
        sb.append(totalTree);
        sb.append("|");
        sb.append(isManager);
        sb.append("|");
        sb.append(status);
        sb.append("|");
        sb.append(createDate);
        sb.append("|");
        sb.append(isDelete);
        sb.append("|");
        sb.append(updateDate);
        return sb.toString(); 
    } 


}
