/*
 * Created on 13 thg 12 2017 ( Time 12:02:52 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.ecomileage.bean;

import java.io.Serializable;

import javax.validation.constraints.*;
import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;
import java.util.Date;
@DynamicInsert
@DynamicUpdate
public class User implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @NotNull
    private Integer id;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Size( max = 100 )
    private String username;


    private Integer roleId;


    private Short status;

    @Size( max = 500 )
    private String password;

    @Size( max = 500 )
    private String passwordTemp;

    @Size( max = 255 )
    private String fullname;

    @NotNull
    private Boolean gender;


    private Date dayOfBirth;

    @Size( max = 200 )
    private String phone;

    @Size( max = 255 )
    private String email;

    @Size( max = 10 )
    private String postcode;

    @Size( max = 300 )
    private String address;

    @Size( max = 100 )
    private String city;

    @Size( max = 100 )
    private String district;

    @Size( max = 300 )
    private String addressDetail;

    @Size( max = 500 )
    private String avatarName;

    @Size( max = 500 )
    private String avatarUrl;

    @Size( max = 50 )
    private String snsType;

    @Size( max = 50 )
    private String socialId;

    @NotNull
    private Integer previousPoint;

    @NotNull
    private Integer bikePoint;

    @NotNull
    private Integer favouritePoint;

    @NotNull
    private Integer transferPoint;

    @Size( max = 500 )
    private String memo;

    @NotNull
    private Float totalMileage;

    @NotNull
    private Float totalMileageOld;

    @NotNull
    private Float totalReduceCo2;

    @NotNull
    private Float totalReduceCo2Old;


    private Integer totalActive;


    private Integer totalActiveOld;


    private Date leavingDate;

    @NotNull
    private Integer totalGoalTree;

    @Size( max = 300 )
    private String leavingReason;

    @NotNull
    private Boolean isDelete;

    @NotNull
    private Boolean loginFirst;


    private Date requestDate;

    @NotNull
    private Short certificateBikeType;

    @NotNull
    private Short certificateTranferType;

    @NotNull
    private Short certificateTranferWifi;


    private Date createDate;


    private Date updateDate;

    @Size( max = 255 )
    private String snsToken;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id ) {
        this.id = id ;
    }

    public Integer getId() {
        return this.id;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setUsername( String username ) {
        this.username = username;
    }
    public String getUsername() {
        return this.username;
    }

    public void setRoleId( Integer roleId ) {
        this.roleId = roleId;
    }
    public Integer getRoleId() {
        return this.roleId;
    }

    public void setStatus( Short status ) {
        this.status = status;
    }
    public Short getStatus() {
        return this.status;
    }

    public void setPassword( String password ) {
        this.password = password;
    }
    public String getPassword() {
        return this.password;
    }

    public void setPasswordTemp( String passwordTemp ) {
        this.passwordTemp = passwordTemp;
    }
    public String getPasswordTemp() {
        return this.passwordTemp;
    }

    public void setFullname( String fullname ) {
        this.fullname = fullname;
    }
    public String getFullname() {
        return this.fullname;
    }

    public void setGender( Boolean gender ) {
        this.gender = gender;
    }
    public Boolean getGender() {
        return this.gender;
    }

    public void setDayOfBirth( Date dayOfBirth ) {
        this.dayOfBirth = dayOfBirth;
    }
    public Date getDayOfBirth() {
        return this.dayOfBirth;
    }

    public void setPhone( String phone ) {
        this.phone = phone;
    }
    public String getPhone() {
        return this.phone;
    }

    public void setEmail( String email ) {
        this.email = email;
    }
    public String getEmail() {
        return this.email;
    }

    public void setPostcode( String postcode ) {
        this.postcode = postcode;
    }
    public String getPostcode() {
        return this.postcode;
    }

    public void setAddress( String address ) {
        this.address = address;
    }
    public String getAddress() {
        return this.address;
    }

    public void setCity( String city ) {
        this.city = city;
    }
    public String getCity() {
        return this.city;
    }

    public void setDistrict( String district ) {
        this.district = district;
    }
    public String getDistrict() {
        return this.district;
    }

    public void setAddressDetail( String addressDetail ) {
        this.addressDetail = addressDetail;
    }
    public String getAddressDetail() {
        return this.addressDetail;
    }

    public void setAvatarName( String avatarName ) {
        this.avatarName = avatarName;
    }
    public String getAvatarName() {
        return this.avatarName;
    }

    public void setAvatarUrl( String avatarUrl ) {
        this.avatarUrl = avatarUrl;
    }
    public String getAvatarUrl() {
        return this.avatarUrl;
    }

    public void setSnsType( String snsType ) {
        this.snsType = snsType;
    }
    public String getSnsType() {
        return this.snsType;
    }

    public void setSocialId( String socialId ) {
        this.socialId = socialId;
    }
    public String getSocialId() {
        return this.socialId;
    }

    public void setPreviousPoint( Integer previousPoint ) {
        this.previousPoint = previousPoint;
    }
    public Integer getPreviousPoint() {
        return this.previousPoint;
    }

    public void setBikePoint( Integer bikePoint ) {
        this.bikePoint = bikePoint;
    }
    public Integer getBikePoint() {
        return this.bikePoint;
    }

    public void setFavouritePoint( Integer favouritePoint ) {
        this.favouritePoint = favouritePoint;
    }
    public Integer getFavouritePoint() {
        return this.favouritePoint;
    }

    public void setTransferPoint( Integer transferPoint ) {
        this.transferPoint = transferPoint;
    }
    public Integer getTransferPoint() {
        return this.transferPoint;
    }

    public void setMemo( String memo ) {
        this.memo = memo;
    }
    public String getMemo() {
        return this.memo;
    }

    public void setTotalMileage( Float totalMileage ) {
        this.totalMileage = totalMileage;
    }
    public Float getTotalMileage() {
        return this.totalMileage;
    }

    public void setTotalMileageOld( Float totalMileageOld ) {
        this.totalMileageOld = totalMileageOld;
    }
    public Float getTotalMileageOld() {
        return this.totalMileageOld;
    }

    public void setTotalReduceCo2( Float totalReduceCo2 ) {
        this.totalReduceCo2 = totalReduceCo2;
    }
    public Float getTotalReduceCo2() {
        return this.totalReduceCo2;
    }

    public void setTotalReduceCo2Old( Float totalReduceCo2Old ) {
        this.totalReduceCo2Old = totalReduceCo2Old;
    }
    public Float getTotalReduceCo2Old() {
        return this.totalReduceCo2Old;
    }

    public void setTotalActive( Integer totalActive ) {
        this.totalActive = totalActive;
    }
    public Integer getTotalActive() {
        return this.totalActive;
    }

    public void setTotalActiveOld( Integer totalActiveOld ) {
        this.totalActiveOld = totalActiveOld;
    }
    public Integer getTotalActiveOld() {
        return this.totalActiveOld;
    }

    public void setLeavingDate( Date leavingDate ) {
        this.leavingDate = leavingDate;
    }
    public Date getLeavingDate() {
        return this.leavingDate;
    }

    public void setTotalGoalTree( Integer totalGoalTree ) {
        this.totalGoalTree = totalGoalTree;
    }
    public Integer getTotalGoalTree() {
        return this.totalGoalTree;
    }

    public void setLeavingReason( String leavingReason ) {
        this.leavingReason = leavingReason;
    }
    public String getLeavingReason() {
        return this.leavingReason;
    }

    public void setIsDelete( Boolean isDelete ) {
        this.isDelete = isDelete;
    }
    public Boolean getIsDelete() {
        return this.isDelete;
    }

    public void setLoginFirst( Boolean loginFirst ) {
        this.loginFirst = loginFirst;
    }
    public Boolean getLoginFirst() {
        return this.loginFirst;
    }

    public void setRequestDate( Date requestDate ) {
        this.requestDate = requestDate;
    }
    public Date getRequestDate() {
        return this.requestDate;
    }

    public void setCertificateBikeType( Short certificateBikeType ) {
        this.certificateBikeType = certificateBikeType;
    }
    public Short getCertificateBikeType() {
        return this.certificateBikeType;
    }

    public void setCertificateTranferType( Short certificateTranferType ) {
        this.certificateTranferType = certificateTranferType;
    }
    public Short getCertificateTranferType() {
        return this.certificateTranferType;
    }

    public void setCertificateTranferWifi( Short certificateTranferWifi ) {
        this.certificateTranferWifi = certificateTranferWifi;
    }
    public Short getCertificateTranferWifi() {
        return this.certificateTranferWifi;
    }

    public void setCreateDate( Date createDate ) {
        this.createDate = createDate;
    }
    public Date getCreateDate() {
        return this.createDate;
    }

    public void setUpdateDate( Date updateDate ) {
        this.updateDate = updateDate;
    }
    public Date getUpdateDate() {
        return this.updateDate;
    }

    public void setSnsToken( String snsToken ) {
        this.snsToken = snsToken;
    }
    public String getSnsToken() {
        return this.snsToken;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
        public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(id);
        sb.append("|");
        sb.append(username);
        sb.append("|");
        sb.append(roleId);
        sb.append("|");
        sb.append(status);
        sb.append("|");
        sb.append(password);
        sb.append("|");
        sb.append(passwordTemp);
        sb.append("|");
        sb.append(fullname);
        sb.append("|");
        sb.append(gender);
        sb.append("|");
        sb.append(dayOfBirth);
        sb.append("|");
        sb.append(phone);
        sb.append("|");
        sb.append(email);
        sb.append("|");
        sb.append(postcode);
        sb.append("|");
        sb.append(address);
        sb.append("|");
        sb.append(city);
        sb.append("|");
        sb.append(district);
        sb.append("|");
        sb.append(addressDetail);
        sb.append("|");
        sb.append(avatarName);
        sb.append("|");
        sb.append(avatarUrl);
        sb.append("|");
        sb.append(snsType);
        sb.append("|");
        sb.append(socialId);
        sb.append("|");
        sb.append(previousPoint);
        sb.append("|");
        sb.append(bikePoint);
        sb.append("|");
        sb.append(favouritePoint);
        sb.append("|");
        sb.append(transferPoint);
        sb.append("|");
        sb.append(memo);
        sb.append("|");
        sb.append(totalMileage);
        sb.append("|");
        sb.append(totalMileageOld);
        sb.append("|");
        sb.append(totalReduceCo2);
        sb.append("|");
        sb.append(totalReduceCo2Old);
        sb.append("|");
        sb.append(totalActive);
        sb.append("|");
        sb.append(totalActiveOld);
        sb.append("|");
        sb.append(leavingDate);
        sb.append("|");
        sb.append(totalGoalTree);
        sb.append("|");
        sb.append(leavingReason);
        sb.append("|");
        sb.append(isDelete);
        sb.append("|");
        sb.append(loginFirst);
        sb.append("|");
        sb.append(requestDate);
        sb.append("|");
        sb.append(certificateBikeType);
        sb.append("|");
        sb.append(certificateTranferType);
        sb.append("|");
        sb.append(certificateTranferWifi);
        sb.append("|");
        sb.append(createDate);
        sb.append("|");
        sb.append(updateDate);
        sb.append("|");
        sb.append(snsToken);
        return sb.toString(); 
    } 


}
