/*
 * Created on 7 thg 12 2017 ( Time 10:30:53 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.ecomileage.bean;

import java.io.Serializable;

import javax.validation.constraints.*;
import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;
import java.util.Date;
@DynamicInsert
@DynamicUpdate
public class VehicleCode implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @NotNull
    private Integer id;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    

    private Integer userId;

    @Size( max = 50 )
    private String serialNumber;

    @Size( max = 200 )
    private String busCompanyName;

    @Size( max = 50 )
    private String busNo;

    @Size( max = 50 )
    private String busNumber;

    @Size( max = 50 )
    private String subwayLineNo;

    @Size( max = 200 )
    private String subwayStationName;

    @Size( max = 200 )
    private String subwayDirection;

    @Size( max = 100 )
    private String subwayDoorNo;

    @Size( max = 200 )
    private String location;

    @Size( max = 20 )
    private String phone;

    @Size( max = 20 )
    private String postCode;


    private Short status;

    @NotNull
    private Short typeVehicle;


    private Short typeSend;


    private Short typeRegister;


    private Short typeCertificate;

    @Size( max = 500 )
    private String imageName;

    @Size( max = 500 )
    private String imageUrl;


    private Date registerDate;


    private Date approvalDate;


    private Date createDate;


    private Date updateDate;

    @Size( max = 500 )
    private String reason;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id ) {
        this.id = id ;
    }

    public Integer getId() {
        return this.id;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setUserId( Integer userId ) {
        this.userId = userId;
    }
    public Integer getUserId() {
        return this.userId;
    }

    public void setSerialNumber( String serialNumber ) {
        this.serialNumber = serialNumber;
    }
    public String getSerialNumber() {
        return this.serialNumber;
    }

    public void setBusCompanyName( String busCompanyName ) {
        this.busCompanyName = busCompanyName;
    }
    public String getBusCompanyName() {
        return this.busCompanyName;
    }

    public void setBusNo( String busNo ) {
        this.busNo = busNo;
    }
    public String getBusNo() {
        return this.busNo;
    }

    public void setBusNumber( String busNumber ) {
        this.busNumber = busNumber;
    }
    public String getBusNumber() {
        return this.busNumber;
    }

    public void setSubwayLineNo( String subwayLineNo ) {
        this.subwayLineNo = subwayLineNo;
    }
    public String getSubwayLineNo() {
        return this.subwayLineNo;
    }

    public void setSubwayStationName( String subwayStationName ) {
        this.subwayStationName = subwayStationName;
    }
    public String getSubwayStationName() {
        return this.subwayStationName;
    }

    public void setSubwayDirection( String subwayDirection ) {
        this.subwayDirection = subwayDirection;
    }
    public String getSubwayDirection() {
        return this.subwayDirection;
    }

    public void setSubwayDoorNo( String subwayDoorNo ) {
        this.subwayDoorNo = subwayDoorNo;
    }
    public String getSubwayDoorNo() {
        return this.subwayDoorNo;
    }

    public void setLocation( String location ) {
        this.location = location;
    }
    public String getLocation() {
        return this.location;
    }

    public void setPhone( String phone ) {
        this.phone = phone;
    }
    public String getPhone() {
        return this.phone;
    }

    public void setPostCode( String postCode ) {
        this.postCode = postCode;
    }
    public String getPostCode() {
        return this.postCode;
    }

    public void setStatus( Short status ) {
        this.status = status;
    }
    public Short getStatus() {
        return this.status;
    }

    public void setTypeVehicle( Short typeVehicle ) {
        this.typeVehicle = typeVehicle;
    }
    public Short getTypeVehicle() {
        return this.typeVehicle;
    }

    public void setTypeSend( Short typeSend ) {
        this.typeSend = typeSend;
    }
    public Short getTypeSend() {
        return this.typeSend;
    }

    public void setTypeRegister( Short typeRegister ) {
        this.typeRegister = typeRegister;
    }
    public Short getTypeRegister() {
        return this.typeRegister;
    }

    public void setTypeCertificate( Short typeCertificate ) {
        this.typeCertificate = typeCertificate;
    }
    public Short getTypeCertificate() {
        return this.typeCertificate;
    }

    public void setImageName( String imageName ) {
        this.imageName = imageName;
    }
    public String getImageName() {
        return this.imageName;
    }

    public void setImageUrl( String imageUrl ) {
        this.imageUrl = imageUrl;
    }
    public String getImageUrl() {
        return this.imageUrl;
    }

    public void setRegisterDate( Date registerDate ) {
        this.registerDate = registerDate;
    }
    public Date getRegisterDate() {
        return this.registerDate;
    }

    public void setApprovalDate( Date approvalDate ) {
        this.approvalDate = approvalDate;
    }
    public Date getApprovalDate() {
        return this.approvalDate;
    }

    public void setCreateDate( Date createDate ) {
        this.createDate = createDate;
    }
    public Date getCreateDate() {
        return this.createDate;
    }

    public void setUpdateDate( Date updateDate ) {
        this.updateDate = updateDate;
    }
    public Date getUpdateDate() {
        return this.updateDate;
    }

    public void setReason( String reason ) {
        this.reason = reason;
    }
    public String getReason() {
        return this.reason;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
        public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(id);
        sb.append("|");
        sb.append(userId);
        sb.append("|");
        sb.append(serialNumber);
        sb.append("|");
        sb.append(busCompanyName);
        sb.append("|");
        sb.append(busNo);
        sb.append("|");
        sb.append(busNumber);
        sb.append("|");
        sb.append(subwayLineNo);
        sb.append("|");
        sb.append(subwayStationName);
        sb.append("|");
        sb.append(subwayDirection);
        sb.append("|");
        sb.append(subwayDoorNo);
        sb.append("|");
        sb.append(location);
        sb.append("|");
        sb.append(phone);
        sb.append("|");
        sb.append(postCode);
        sb.append("|");
        sb.append(status);
        sb.append("|");
        sb.append(typeVehicle);
        sb.append("|");
        sb.append(typeSend);
        sb.append("|");
        sb.append(typeRegister);
        sb.append("|");
        sb.append(typeCertificate);
        sb.append("|");
        sb.append(imageName);
        sb.append("|");
        sb.append(imageUrl);
        sb.append("|");
        sb.append(registerDate);
        sb.append("|");
        sb.append(approvalDate);
        sb.append("|");
        sb.append(createDate);
        sb.append("|");
        sb.append(updateDate);
        sb.append("|");
        sb.append(reason);
        return sb.toString(); 
    } 


}
