/*
 * Created on 31 thg 10 2017 ( Time 13:31:30 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.ecomileage.business.service;

import java.util.List;
import java.util.Map;
import org.ecomileage.bean.jpa.MileageTransferEntity;
import org.ecomileage.bean.MileageTransfer;
import org.springframework.data.domain.Page;

/**
 * Business Service Interface for entity MileageTransfer.
 */
public interface MileageTransferService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param id
	 * @return entity
	 */
	MileageTransfer findById( Integer id  ) ;

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param id
	 * @return entity
	 */
	MileageTransferEntity findOne( Integer id  ) ;

	/** 
	 * Loads all entities.
	 * @return all entities
	 */
	List<MileageTransfer> findAll();
	
	/**
	 * Loads entities in page number.
	 * @return entities
	 */

	Page<MileageTransferEntity> findAll(Integer page);

	/**
	 * Count all entities
	 * @return Long
	 */
	Long countTotal();
	

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	MileageTransfer save(MileageTransfer entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	MileageTransfer update(MileageTransfer entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	MileageTransfer create(MileageTransfer entity);
	
	/**
	 * Deletes an entity using its Primary Key
	 * @param id
	 */
	void delete( Integer id );

	Page<MileageTransferEntity> listPaging(Integer page,Integer size);
	
	Page<MileageTransferEntity> listPagingByUserId( Integer page, Integer size, Integer userId);



	Page<MileageTransferEntity> filterAdmin( Map<String, Object> params, Integer page, Integer size);
}
