/*
 * Created on 7 thg 12 2017 ( Time 17:30:58 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.ecomileage.business.service;

import java.util.Date;
import java.util.List;
import java.util.Map;
import org.ecomileage.bean.jpa.PaymentEntity;
import org.ecomileage.bean.Payment;
import org.springframework.data.domain.Page;

/**
 * Business Service Interface for entity Payment.
 */
public interface PaymentService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param id
	 * @return entity
	 */
	Payment findById( Integer id  ) ;

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param id
	 * @return entity
	 */
	PaymentEntity findOne( Integer id  ) ;

	/** 
	 * Loads all entities.
	 * @return all entities
	 */
	List<Payment> findAll();
	
	/**
	 * Loads entities in page number.
	 * @return entities
	 */

	Page<PaymentEntity> findAll(Integer page);

	/**
	 * Count all entities
	 * @return Long
	 */
	Long countTotal();
	

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	Payment save(Payment entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	Payment update(Payment entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	Payment create(Payment entity);
	
	/**
	 * Deletes an entity using its Primary Key
	 * @param id
	 */
	void delete( Integer id );

	Page<PaymentEntity> listPaging(Integer page,Integer size);

	Page<PaymentEntity> filterAdmin( Map<String, Object> params, Integer page, Integer size);
	
	List<PaymentEntity> listPagingBy_UserIdAndTypeMoney(Integer userId, Short typeMoney);
	
	List<Map<String,Object>> listSponsorBy_TypeSponsorAndMonth(Short typeSponsor, Date date);
	
	Long getTotalSponsor(Date date);
	
	List<PaymentEntity> listPagingBy_MonthAndYear(Date date);
	
	Long getTotalMoney(Map<String, Object> params);
	
	Long getTotalMoneyTem(Map<String, Object> params);
	
	PaymentEntity findByMileageApplyId(Integer mileageApplyId);
	
	Long getTotalSponsorBy_TypeSponsor(Short typeSponsor);
}
