/*
 * Created on 2 thg 10 2017 ( Time 15:10:01 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.ecomileage.business.service;

import java.util.List;
import java.util.Map;
import org.ecomileage.bean.jpa.ReportEntity;
import org.ecomileage.bean.Report;
import org.springframework.data.domain.Page;

/**
 * Business Service Interface for entity Report.
 */
public interface ReportService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param id
	 * @return entity
	 */
	Report findById( Integer id  ) ;

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param id
	 * @return entity
	 */
	ReportEntity findOne( Integer id  ) ;

	/** 
	 * Loads all entities.
	 * @return all entities
	 */
	List<Report> findAll();
	
	/**
	 * Loads entities in page number.
	 * @return entities
	 */

	Page<ReportEntity> findAll(Integer page);

	/**
	 * Count all entities
	 * @return Long
	 */
	Long countTotal();
	

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	Report save(Report entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	Report update(Report entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	Report create(Report entity);
	
	/**
	 * Deletes an entity using its Primary Key
	 * @param id
	 */
	void delete( Integer id );

	Page<ReportEntity> listPaging(Integer page,Integer size);
	


	Page<ReportEntity> filterAdmin( Map<String, Object> params, Integer page, Integer size);
}
