/*
 * Created on 2 thg 10 2017 ( Time 15:10:01 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.ecomileage.business.service;

import java.util.Date;
import java.util.List;
import java.util.Map;
import org.ecomileage.bean.jpa.SettingEntity;
import org.ecomileage.bean.Setting;
import org.springframework.data.domain.Page;

/**
 * Business Service Interface for entity Setting.
 */
public interface SettingService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param id
	 * @return entity
	 */
	Setting findById( Integer id  ) ;

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param id
	 * @return entity
	 */
	SettingEntity findOne( Integer id  ) ;

	/** 
	 * Loads all entities.
	 * @return all entities
	 */
	List<Setting> findAll();
	
	/**
	 * Loads entities in page number.
	 * @return entities
	 */

	Page<SettingEntity> findAll(Integer page);

	/**
	 * Count all entities
	 * @return Long
	 */
	Long countTotal();
	

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	Setting save(Setting entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	Setting update(Setting entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	Setting create(Setting entity);
	
	/**
	 * Deletes an entity using its Primary Key
	 * @param id
	 */
	void delete( Integer id );

	Page<SettingEntity> listPaging(Integer page,Integer size);

	Page<SettingEntity> filterAdmin( Map<String, Object> params, Integer page, Integer size);
	
	List<SettingEntity> findByDate(Date now);
	
	boolean checkDuplicateStartDateAndEndDate(Date startDate, Date endDate, Integer id);
	
	boolean checkDuplicateStartDateAndEndDate(Date startDate, Date endDate);
}
