/*
 * Created on 2 thg 10 2017 ( Time 15:10:01 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.ecomileage.business.service;

import java.util.Date;
import java.util.List;
import java.util.Map;
import org.ecomileage.bean.jpa.TeamEntity;
import org.ecomileage.web.common.PageCustom;
import org.ecomileage.bean.Group;
import org.ecomileage.bean.Team;
import org.springframework.data.domain.Page;

/**
 * Business Service Interface for entity Team.
 */
public interface TeamService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param id
	 * @return entity
	 */
	Team findById( Integer id  ) ;

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param id
	 * @return entity
	 */
	TeamEntity findOne( Integer id  ) ;

	/** 
	 * Loads all entities.
	 * @return all entities
	 */
	List<Team> findAll();
	
	/**
	 * Loads entities in page number.
	 * @return entities
	 */

	Page<TeamEntity> findAll(Integer page);

	/**
	 * Count all entities
	 * @return Long
	 */
	Long countTotal();
	

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	Team save(Team entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	Team update(Team entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	Team create(Team entity);
	
	/**
	 * Deletes an entity using its Primary Key
	 * @param id
	 */
	void delete( Integer id );

	Page<TeamEntity> listPaging(Integer page,Integer size);
	
	void update_isDelete(Integer id);
	
	Page<TeamEntity> filterAdmin( Map<String, Object> params, Integer page, Integer size);
	
	PageCustom<Map<String,Object>> listPagingCustom(Map<String, Object> params, Integer page, Integer size);
	
	PageCustom<Map<String,Object>> listPagingAdminCustom(Map<String, Object> params, Integer page, Integer size);
	
	List<Map<String,Object>> listMyGroup(Map<String, Object> params);
	
	List<TeamEntity> findByName(String name);
	
	List<TeamEntity> listByDeleteDate(Date date);
}
