/*
 * Created on 2 thg 10 2017 ( Time 15:10:01 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.ecomileage.business.service;

import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.ecomileage.bean.jpa.TeamMemberEntity;
import org.ecomileage.bean.TeamMember;
import org.springframework.data.domain.Page;

/**
 * Business Service Interface for entity TeamMember.
 */
public interface TeamMemberService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param id
	 * @return entity
	 */
	TeamMember findById( Integer id  ) ;

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param id
	 * @return entity
	 */
	TeamMemberEntity findOne( Integer id  ) ;

	/** 
	 * Loads all entities.
	 * @return all entities
	 */
	List<TeamMember> findAll();
	
	/**
	 * Loads entities in page number.
	 * @return entities
	 */

	Page<TeamMemberEntity> findAll(Integer page);

	/**
	 * Count all entities
	 * @return Long
	 */
	Long countTotal();
	

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	TeamMember save(TeamMember entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	TeamMember update(TeamMember entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	TeamMember create(TeamMember entity);
	
	/**
	 * Deletes an entity using its Primary Key
	 * @param id
	 */
	void delete( Integer id );

	Page<TeamMemberEntity> listPaging(Integer page,Integer size);

	Page<TeamMemberEntity> filterAdmin( Map<String, Object> params, Integer page, Integer size);
	
	List<TeamMemberEntity> findByUserId(Integer userId);
	
	List<Map<String, Object>> findByGroupId(Integer groupId);

	Long countMemberByGroupId(Integer groupId);
	
	Long countCO2ByGroupId(Integer groupId);
	
	TeamMemberEntity findByUserIdAndGroupId(Integer userId, Integer groupId);
	
	void update_isDelete_byGroupId(Integer id);
	
	void update_isDelete_byGroupIdAndUserId(Integer groupId, Integer userId);
	
	TeamMemberEntity update(TeamMemberEntity teamMemberEntity);
	
	void update_TranformManager(Integer groupId, Integer mangerId);
	
	Long countGroupByUserId(Integer userId);
	
	void update_Manager(Integer groupId, Integer mangerId);
}
