/*
 * Created on 2 thg 10 2017 ( Time 15:10:02 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.ecomileage.business.service;

import java.util.List;
import java.util.Map;
import org.ecomileage.bean.jpa.VehicleCodeEntity;
import org.ecomileage.bean.VehicleCode;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

/**
 * Business Service Interface for entity VehicleCode.
 */
public interface VehicleCodeService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param id
	 * @return entity
	 */
	VehicleCode findById( Integer id  ) ;

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param id
	 * @return entity
	 */
	VehicleCodeEntity findOne( Integer id  ) ;

	/** 
	 * Loads all entities.
	 * @return all entities
	 */
	List<VehicleCode> findAll();
	
	/**
	 * Loads entities in page number.
	 * @return entities
	 */

	Page<VehicleCodeEntity> findAll(Integer page);

	/**
	 * Count all entities
	 * @return Long
	 */
	Long countTotal();
	

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	VehicleCode save(VehicleCode entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	VehicleCode update(VehicleCode entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	VehicleCode create(VehicleCode entity);
	
	/**
	 * Deletes an entity using its Primary Key
	 * @param id
	 */
	void delete( Integer id );

	Page<VehicleCodeEntity> listPaging(Integer page,Integer size);

	Page<VehicleCodeEntity> filterAdmin( Map<String, Object> params, Integer page, Integer size);
	
	List<VehicleCodeEntity> findTypeVehicleAndUserId(Short[] typeVehicle, Integer userId);
	
	VehicleCodeEntity findByUserId(Integer userId);
	
	VehicleCode findBySerialNumberAndUserId(String serialNumber , Integer userId);
	
	VehicleCode findBySerialNumberAndTypeVehicle(String serialNumber , Short typeVehicle);
	
	VehicleCode findBySerialNumber(String serialNumber);
	
	VehicleCode findBySerialNumberByBusAndSubway(String serialNumber);
	
	Long countByTypeVehicle(Short typeVehicle);
	
}
