/*
 * Created on 4 May 2015 ( Time 15:47:17 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.ecomileage.rest.common;


import java.util.HashMap;
import org.springframework.http.HttpStatus;

public abstract class AbstractRestController {
	
	public static HashMap<String, Object> SUCCESS(Object data)
	{HashMap<String, Object> ret = new HashMap<String, Object> ();
		ret.put("code", HttpStatus.OK.value());
		ret.put("message", "Process success!");
		ret.put("data", data);
		System.out.println("success:"+ret.toString());
		return ret;
	}
	
	public static HashMap<String, Object> SUCCESS()
	{HashMap<String, Object> ret = new HashMap<String, Object> ();
		ret.put("code", HttpStatus.OK.value());
		ret.put("message", "Process success!");
		ret.put("data", null);
		System.out.println("success:"+ret.toString());
		return ret;
	}
	
	public static HashMap<String, Object> SUCCESS(Object data,String message)
	{
		HashMap<String, Object> ret = new HashMap<String, Object> ();
		ret.put("code", HttpStatus.OK.value());
		ret.put("message", message);
		ret.put("data", data);
		System.out.println("success:"+ret.toString());
		return ret;
	}
	
	public static HashMap<String, Object> FAIL(String message)
	{
		HashMap<String, Object> ret = new HashMap<String, Object> ();
		ret.put("code", HttpStatus.NOT_FOUND.value());
		ret.put("message", message);
		ret.put("data", null);
		System.out.println("fail:"+ret.toString());
		return ret;
	}
	
	public static HashMap<String, Object> FAIL(Object data)
	{
		HashMap<String, Object> ret = new HashMap<String, Object> ();
		ret.put("code", HttpStatus.NOT_FOUND.value());
		ret.put("data", data);
		ret.put("message", "Not found!");
		System.out.println("fail:"+ret.toString());
		return ret;
	}
	
	public static HashMap<String, Object> RESULT_CODE(int code, String message)
	{
		HashMap<String, Object> ret = new HashMap<String, Object> ();
		ret.put("code", code);
		ret.put("data", null);
		ret.put("message", message);
		return ret;
	}
	
	public static HashMap<String, Object> FAIL()
	{
		HashMap<String, Object> ret = new HashMap<String, Object> ();
		ret.put("code", HttpStatus.NOT_FOUND.value());
		ret.put("data", null);
		ret.put("message", "Not found!");
		System.out.println("fail:"+ret.toString());
		return ret;
	}
	
	public static HashMap<String, Object> ERROR(String message)
	{
		HashMap<String, Object> ret = new HashMap<String, Object> ();
		ret.put("code", HttpStatus.INTERNAL_SERVER_ERROR.value());
		ret.put("data", null);
		ret.put("message", message);
		System.out.println("fail:"+ret.toString());
		return ret;
	}
	
}