/*
 * Created on 31 thg 10 2017 ( Time 13:31:30 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.ecomileage.business.service.mapping;

import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import org.ecomileage.bean.MileageTransfer;
import org.ecomileage.bean.jpa.MileageTransferEntity;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class MileageTransferServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public MileageTransferServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'MileageTransferEntity' to 'MileageTransfer'
	 * @param mileageTransferEntity
	 */
	public MileageTransfer mapMileageTransferEntityToMileageTransfer(MileageTransferEntity mileageTransferEntity) {
		if(mileageTransferEntity == null) {
			return null;
		}

		//--- Generic mapping 
		MileageTransfer mileageTransfer = map(mileageTransferEntity, MileageTransfer.class);

		return mileageTransfer;
	}
	
	/**
	 * Mapping from 'MileageTransfer' to 'MileageTransferEntity'
	 * @param mileageTransfer
	 * @param mileageTransferEntity
	 */
	public void mapMileageTransferToMileageTransferEntity(MileageTransfer mileageTransfer, MileageTransferEntity mileageTransferEntity) {
		if(mileageTransfer == null) {
			return;
		}

		//--- Generic mapping 
		map(mileageTransfer, mileageTransferEntity);

	}
	
	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}